/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package person077;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Data extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2238440271785700240L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Data\",\"namespace\":\"person077\",\"fields\":[{\"name\":\"KVHX\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"KOMMUNE_KODE\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"VEJ_KODE\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"HUSNR\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ETAGE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"SIDE_DOER\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STEDNAVN\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"BYNAVN\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"SOGN\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"REGION\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"EJENDOM_BBR\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"EJENDOM_ESR\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"ADGANG_OPRINDELSE\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"ENHED_OPRINDELSE\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"BBR_BRUG\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"KOORDINAT_KVALITET\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"X_KOORDINAT\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"Y_KOORDINAT\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"OPRET_SBH\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"OPRET_TIMESTAMP\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"RET_SBH\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"RET_TIMESTAMP\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence KVHX;
  @Deprecated public Integer KOMMUNE_KODE;
  @Deprecated public Integer VEJ_KODE;
  @Deprecated public CharSequence HUSNR;
  @Deprecated public CharSequence ETAGE;
  @Deprecated public CharSequence SIDE_DOER;
  @Deprecated public CharSequence STEDNAVN;
  @Deprecated public CharSequence BYNAVN;
  @Deprecated public CharSequence SOGN;
  @Deprecated public CharSequence REGION;
  @Deprecated public Integer EJENDOM_BBR;
  @Deprecated public Integer EJENDOM_ESR;
  @Deprecated public Integer ADGANG_OPRINDELSE;
  @Deprecated public Integer ENHED_OPRINDELSE;
  @Deprecated public Integer BBR_BRUG;
  @Deprecated public Integer KOORDINAT_KVALITET;
  @Deprecated public Integer X_KOORDINAT;
  @Deprecated public Integer Y_KOORDINAT;
  @Deprecated public CharSequence OPRET_SBH;
  @Deprecated public CharSequence OPRET_TIMESTAMP;
  @Deprecated public CharSequence RET_SBH;
  @Deprecated public CharSequence RET_TIMESTAMP;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Data() {}

  /**
   * All-args constructor.
   * @param KVHX The new value for KVHX
   * @param KOMMUNE_KODE The new value for KOMMUNE_KODE
   * @param VEJ_KODE The new value for VEJ_KODE
   * @param HUSNR The new value for HUSNR
   * @param ETAGE The new value for ETAGE
   * @param SIDE_DOER The new value for SIDE_DOER
   * @param STEDNAVN The new value for STEDNAVN
   * @param BYNAVN The new value for BYNAVN
   * @param SOGN The new value for SOGN
   * @param REGION The new value for REGION
   * @param EJENDOM_BBR The new value for EJENDOM_BBR
   * @param EJENDOM_ESR The new value for EJENDOM_ESR
   * @param ADGANG_OPRINDELSE The new value for ADGANG_OPRINDELSE
   * @param ENHED_OPRINDELSE The new value for ENHED_OPRINDELSE
   * @param BBR_BRUG The new value for BBR_BRUG
   * @param KOORDINAT_KVALITET The new value for KOORDINAT_KVALITET
   * @param X_KOORDINAT The new value for X_KOORDINAT
   * @param Y_KOORDINAT The new value for Y_KOORDINAT
   * @param OPRET_SBH The new value for OPRET_SBH
   * @param OPRET_TIMESTAMP The new value for OPRET_TIMESTAMP
   * @param RET_SBH The new value for RET_SBH
   * @param RET_TIMESTAMP The new value for RET_TIMESTAMP
   */
  public Data(CharSequence KVHX, Integer KOMMUNE_KODE, Integer VEJ_KODE, CharSequence HUSNR, CharSequence ETAGE, CharSequence SIDE_DOER, CharSequence STEDNAVN, CharSequence BYNAVN, CharSequence SOGN, CharSequence REGION, Integer EJENDOM_BBR, Integer EJENDOM_ESR, Integer ADGANG_OPRINDELSE, Integer ENHED_OPRINDELSE, Integer BBR_BRUG, Integer KOORDINAT_KVALITET, Integer X_KOORDINAT, Integer Y_KOORDINAT, CharSequence OPRET_SBH, CharSequence OPRET_TIMESTAMP, CharSequence RET_SBH, CharSequence RET_TIMESTAMP) {
    this.KVHX = KVHX;
    this.KOMMUNE_KODE = KOMMUNE_KODE;
    this.VEJ_KODE = VEJ_KODE;
    this.HUSNR = HUSNR;
    this.ETAGE = ETAGE;
    this.SIDE_DOER = SIDE_DOER;
    this.STEDNAVN = STEDNAVN;
    this.BYNAVN = BYNAVN;
    this.SOGN = SOGN;
    this.REGION = REGION;
    this.EJENDOM_BBR = EJENDOM_BBR;
    this.EJENDOM_ESR = EJENDOM_ESR;
    this.ADGANG_OPRINDELSE = ADGANG_OPRINDELSE;
    this.ENHED_OPRINDELSE = ENHED_OPRINDELSE;
    this.BBR_BRUG = BBR_BRUG;
    this.KOORDINAT_KVALITET = KOORDINAT_KVALITET;
    this.X_KOORDINAT = X_KOORDINAT;
    this.Y_KOORDINAT = Y_KOORDINAT;
    this.OPRET_SBH = OPRET_SBH;
    this.OPRET_TIMESTAMP = OPRET_TIMESTAMP;
    this.RET_SBH = RET_SBH;
    this.RET_TIMESTAMP = RET_TIMESTAMP;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return KVHX;
    case 1: return KOMMUNE_KODE;
    case 2: return VEJ_KODE;
    case 3: return HUSNR;
    case 4: return ETAGE;
    case 5: return SIDE_DOER;
    case 6: return STEDNAVN;
    case 7: return BYNAVN;
    case 8: return SOGN;
    case 9: return REGION;
    case 10: return EJENDOM_BBR;
    case 11: return EJENDOM_ESR;
    case 12: return ADGANG_OPRINDELSE;
    case 13: return ENHED_OPRINDELSE;
    case 14: return BBR_BRUG;
    case 15: return KOORDINAT_KVALITET;
    case 16: return X_KOORDINAT;
    case 17: return Y_KOORDINAT;
    case 18: return OPRET_SBH;
    case 19: return OPRET_TIMESTAMP;
    case 20: return RET_SBH;
    case 21: return RET_TIMESTAMP;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: KVHX = (CharSequence)value$; break;
    case 1: KOMMUNE_KODE = (Integer)value$; break;
    case 2: VEJ_KODE = (Integer)value$; break;
    case 3: HUSNR = (CharSequence)value$; break;
    case 4: ETAGE = (CharSequence)value$; break;
    case 5: SIDE_DOER = (CharSequence)value$; break;
    case 6: STEDNAVN = (CharSequence)value$; break;
    case 7: BYNAVN = (CharSequence)value$; break;
    case 8: SOGN = (CharSequence)value$; break;
    case 9: REGION = (CharSequence)value$; break;
    case 10: EJENDOM_BBR = (Integer)value$; break;
    case 11: EJENDOM_ESR = (Integer)value$; break;
    case 12: ADGANG_OPRINDELSE = (Integer)value$; break;
    case 13: ENHED_OPRINDELSE = (Integer)value$; break;
    case 14: BBR_BRUG = (Integer)value$; break;
    case 15: KOORDINAT_KVALITET = (Integer)value$; break;
    case 16: X_KOORDINAT = (Integer)value$; break;
    case 17: Y_KOORDINAT = (Integer)value$; break;
    case 18: OPRET_SBH = (CharSequence)value$; break;
    case 19: OPRET_TIMESTAMP = (CharSequence)value$; break;
    case 20: RET_SBH = (CharSequence)value$; break;
    case 21: RET_TIMESTAMP = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'KVHX' field.
   * @return The value of the 'KVHX' field.
   */
  public CharSequence getKVHX() {
    return KVHX;
  }

  /**
   * Sets the value of the 'KVHX' field.
   * @param value the value to set.
   */
  public void setKVHX(CharSequence value) {
    this.KVHX = value;
  }

  /**
   * Gets the value of the 'KOMMUNE_KODE' field.
   * @return The value of the 'KOMMUNE_KODE' field.
   */
  public Integer getKOMMUNEKODE() {
    return KOMMUNE_KODE;
  }
  public String getKOMMUNEKODEString() {
    return KOMMUNE_KODE.toString();
  }

  /**
   * Sets the value of the 'KOMMUNE_KODE' field.
   * @param value the value to set.
   */
  public void setKOMMUNEKODE(Integer value) {
    this.KOMMUNE_KODE = value;
  }

  /**
   * Gets the value of the 'VEJ_KODE' field.
   * @return The value of the 'VEJ_KODE' field.
   */
  public Integer getVEJKODE() {
    return VEJ_KODE;
  }

  /**
   * Sets the value of the 'VEJ_KODE' field.
   * @param value the value to set.
   */
  public void setVEJKODE(Integer value) {
    this.VEJ_KODE = value;
  }

  /**
   * Gets the value of the 'HUSNR' field.
   * @return The value of the 'HUSNR' field.
   */
  public CharSequence getHUSNR() {
    return HUSNR;
  }

  /**
   * Sets the value of the 'HUSNR' field.
   * @param value the value to set.
   */
  public void setHUSNR(CharSequence value) {
    this.HUSNR = value;
  }

  /**
   * Gets the value of the 'ETAGE' field.
   * @return The value of the 'ETAGE' field.
   */
  public CharSequence getETAGE() {
    return ETAGE;
  }

  /**
   * Sets the value of the 'ETAGE' field.
   * @param value the value to set.
   */
  public void setETAGE(CharSequence value) {
    this.ETAGE = value;
  }

  /**
   * Gets the value of the 'SIDE_DOER' field.
   * @return The value of the 'SIDE_DOER' field.
   */
  public CharSequence getSIDEDOER() {
    return SIDE_DOER;
  }

  /**
   * Sets the value of the 'SIDE_DOER' field.
   * @param value the value to set.
   */
  public void setSIDEDOER(CharSequence value) {
    this.SIDE_DOER = value;
  }

  /**
   * Gets the value of the 'STEDNAVN' field.
   * @return The value of the 'STEDNAVN' field.
   */
  public CharSequence getSTEDNAVN() {
    return STEDNAVN;
  }

  /**
   * Sets the value of the 'STEDNAVN' field.
   * @param value the value to set.
   */
  public void setSTEDNAVN(CharSequence value) {
    this.STEDNAVN = value;
  }

  /**
   * Gets the value of the 'BYNAVN' field.
   * @return The value of the 'BYNAVN' field.
   */
  public CharSequence getBYNAVN() {
    return BYNAVN;
  }

  /**
   * Sets the value of the 'BYNAVN' field.
   * @param value the value to set.
   */
  public void setBYNAVN(CharSequence value) {
    this.BYNAVN = value;
  }

  /**
   * Gets the value of the 'SOGN' field.
   * @return The value of the 'SOGN' field.
   */
  public CharSequence getSOGN() {
    return SOGN;
  }

  /**
   * Sets the value of the 'SOGN' field.
   * @param value the value to set.
   */
  public void setSOGN(CharSequence value) {
    this.SOGN = value;
  }

  /**
   * Gets the value of the 'REGION' field.
   * @return The value of the 'REGION' field.
   */
  public CharSequence getREGION() {
    return REGION;
  }

  /**
   * Sets the value of the 'REGION' field.
   * @param value the value to set.
   */
  public void setREGION(CharSequence value) {
    this.REGION = value;
  }

  /**
   * Gets the value of the 'EJENDOM_BBR' field.
   * @return The value of the 'EJENDOM_BBR' field.
   */
  public Integer getEJENDOMBBR() {
    return EJENDOM_BBR;
  }

  /**
   * Sets the value of the 'EJENDOM_BBR' field.
   * @param value the value to set.
   */
  public void setEJENDOMBBR(Integer value) {
    this.EJENDOM_BBR = value;
  }

  /**
   * Gets the value of the 'EJENDOM_ESR' field.
   * @return The value of the 'EJENDOM_ESR' field.
   */
  public Integer getEJENDOMESR() {
    return EJENDOM_ESR;
  }

  /**
   * Sets the value of the 'EJENDOM_ESR' field.
   * @param value the value to set.
   */
  public void setEJENDOMESR(Integer value) {
    this.EJENDOM_ESR = value;
  }

  /**
   * Gets the value of the 'ADGANG_OPRINDELSE' field.
   * @return The value of the 'ADGANG_OPRINDELSE' field.
   */
  public Integer getADGANGOPRINDELSE() {
    return ADGANG_OPRINDELSE;
  }

  /**
   * Sets the value of the 'ADGANG_OPRINDELSE' field.
   * @param value the value to set.
   */
  public void setADGANGOPRINDELSE(Integer value) {
    this.ADGANG_OPRINDELSE = value;
  }

  /**
   * Gets the value of the 'ENHED_OPRINDELSE' field.
   * @return The value of the 'ENHED_OPRINDELSE' field.
   */
  public Integer getENHEDOPRINDELSE() {
    return ENHED_OPRINDELSE;
  }

  /**
   * Sets the value of the 'ENHED_OPRINDELSE' field.
   * @param value the value to set.
   */
  public void setENHEDOPRINDELSE(Integer value) {
    this.ENHED_OPRINDELSE = value;
  }

  /**
   * Gets the value of the 'BBR_BRUG' field.
   * @return The value of the 'BBR_BRUG' field.
   */
  public Integer getBBRBRUG() {
    return BBR_BRUG;
  }

  /**
   * Sets the value of the 'BBR_BRUG' field.
   * @param value the value to set.
   */
  public void setBBRBRUG(Integer value) {
    this.BBR_BRUG = value;
  }

  /**
   * Gets the value of the 'KOORDINAT_KVALITET' field.
   * @return The value of the 'KOORDINAT_KVALITET' field.
   */
  public Integer getKOORDINATKVALITET() {
    return KOORDINAT_KVALITET;
  }

  /**
   * Sets the value of the 'KOORDINAT_KVALITET' field.
   * @param value the value to set.
   */
  public void setKOORDINATKVALITET(Integer value) {
    this.KOORDINAT_KVALITET = value;
  }

  /**
   * Gets the value of the 'X_KOORDINAT' field.
   * @return The value of the 'X_KOORDINAT' field.
   */
  public Integer getXKOORDINAT() {
    return X_KOORDINAT;
  }

  /**
   * Sets the value of the 'X_KOORDINAT' field.
   * @param value the value to set.
   */
  public void setXKOORDINAT(Integer value) {
    this.X_KOORDINAT = value;
  }

  /**
   * Gets the value of the 'Y_KOORDINAT' field.
   * @return The value of the 'Y_KOORDINAT' field.
   */
  public Integer getYKOORDINAT() {
    return Y_KOORDINAT;
  }

  /**
   * Sets the value of the 'Y_KOORDINAT' field.
   * @param value the value to set.
   */
  public void setYKOORDINAT(Integer value) {
    this.Y_KOORDINAT = value;
  }

  /**
   * Gets the value of the 'OPRET_SBH' field.
   * @return The value of the 'OPRET_SBH' field.
   */
  public CharSequence getOPRETSBH() {
    return OPRET_SBH;
  }

  /**
   * Sets the value of the 'OPRET_SBH' field.
   * @param value the value to set.
   */
  public void setOPRETSBH(CharSequence value) {
    this.OPRET_SBH = value;
  }

  /**
   * Gets the value of the 'OPRET_TIMESTAMP' field.
   * @return The value of the 'OPRET_TIMESTAMP' field.
   */
  public CharSequence getOPRETTIMESTAMP() {
    return OPRET_TIMESTAMP;
  }

  /**
   * Sets the value of the 'OPRET_TIMESTAMP' field.
   * @param value the value to set.
   */
  public void setOPRETTIMESTAMP(CharSequence value) {
    this.OPRET_TIMESTAMP = value;
  }

  /**
   * Gets the value of the 'RET_SBH' field.
   * @return The value of the 'RET_SBH' field.
   */
  public CharSequence getRETSBH() {
    return RET_SBH;
  }

  /**
   * Sets the value of the 'RET_SBH' field.
   * @param value the value to set.
   */
  public void setRETSBH(CharSequence value) {
    this.RET_SBH = value;
  }

  /**
   * Gets the value of the 'RET_TIMESTAMP' field.
   * @return The value of the 'RET_TIMESTAMP' field.
   */
  public CharSequence getRETTIMESTAMP() {
    return RET_TIMESTAMP;
  }

  /**
   * Sets the value of the 'RET_TIMESTAMP' field.
   * @param value the value to set.
   */
  public void setRETTIMESTAMP(CharSequence value) {
    this.RET_TIMESTAMP = value;
  }

  /**
   * Creates a new Data RecordBuilder.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Data instance.
   * @param other The existing instance to copy.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder(Data other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Data instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Data>
    implements org.apache.avro.data.RecordBuilder<Data> {

    private CharSequence KVHX;
    private Integer KOMMUNE_KODE;
    private Integer VEJ_KODE;
    private CharSequence HUSNR;
    private CharSequence ETAGE;
    private CharSequence SIDE_DOER;
    private CharSequence STEDNAVN;
    private CharSequence BYNAVN;
    private CharSequence SOGN;
    private CharSequence REGION;
    private Integer EJENDOM_BBR;
    private Integer EJENDOM_ESR;
    private Integer ADGANG_OPRINDELSE;
    private Integer ENHED_OPRINDELSE;
    private Integer BBR_BRUG;
    private Integer KOORDINAT_KVALITET;
    private Integer X_KOORDINAT;
    private Integer Y_KOORDINAT;
    private CharSequence OPRET_SBH;
    private CharSequence OPRET_TIMESTAMP;
    private CharSequence RET_SBH;
    private CharSequence RET_TIMESTAMP;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.KVHX)) {
        this.KVHX = data().deepCopy(fields()[0].schema(), other.KVHX);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.KOMMUNE_KODE)) {
        this.KOMMUNE_KODE = data().deepCopy(fields()[1].schema(), other.KOMMUNE_KODE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.VEJ_KODE)) {
        this.VEJ_KODE = data().deepCopy(fields()[2].schema(), other.VEJ_KODE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.HUSNR)) {
        this.HUSNR = data().deepCopy(fields()[3].schema(), other.HUSNR);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ETAGE)) {
        this.ETAGE = data().deepCopy(fields()[4].schema(), other.ETAGE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SIDE_DOER)) {
        this.SIDE_DOER = data().deepCopy(fields()[5].schema(), other.SIDE_DOER);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.STEDNAVN)) {
        this.STEDNAVN = data().deepCopy(fields()[6].schema(), other.STEDNAVN);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.BYNAVN)) {
        this.BYNAVN = data().deepCopy(fields()[7].schema(), other.BYNAVN);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.SOGN)) {
        this.SOGN = data().deepCopy(fields()[8].schema(), other.SOGN);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.REGION)) {
        this.REGION = data().deepCopy(fields()[9].schema(), other.REGION);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.EJENDOM_BBR)) {
        this.EJENDOM_BBR = data().deepCopy(fields()[10].schema(), other.EJENDOM_BBR);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.EJENDOM_ESR)) {
        this.EJENDOM_ESR = data().deepCopy(fields()[11].schema(), other.EJENDOM_ESR);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ADGANG_OPRINDELSE)) {
        this.ADGANG_OPRINDELSE = data().deepCopy(fields()[12].schema(), other.ADGANG_OPRINDELSE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ENHED_OPRINDELSE)) {
        this.ENHED_OPRINDELSE = data().deepCopy(fields()[13].schema(), other.ENHED_OPRINDELSE);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.BBR_BRUG)) {
        this.BBR_BRUG = data().deepCopy(fields()[14].schema(), other.BBR_BRUG);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.KOORDINAT_KVALITET)) {
        this.KOORDINAT_KVALITET = data().deepCopy(fields()[15].schema(), other.KOORDINAT_KVALITET);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.X_KOORDINAT)) {
        this.X_KOORDINAT = data().deepCopy(fields()[16].schema(), other.X_KOORDINAT);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Y_KOORDINAT)) {
        this.Y_KOORDINAT = data().deepCopy(fields()[17].schema(), other.Y_KOORDINAT);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.OPRET_SBH)) {
        this.OPRET_SBH = data().deepCopy(fields()[18].schema(), other.OPRET_SBH);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.OPRET_TIMESTAMP)) {
        this.OPRET_TIMESTAMP = data().deepCopy(fields()[19].schema(), other.OPRET_TIMESTAMP);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RET_SBH)) {
        this.RET_SBH = data().deepCopy(fields()[20].schema(), other.RET_SBH);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.RET_TIMESTAMP)) {
        this.RET_TIMESTAMP = data().deepCopy(fields()[21].schema(), other.RET_TIMESTAMP);
        fieldSetFlags()[21] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Data instance
     * @param other The existing instance to copy.
     */
    private Builder(Data other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.KVHX)) {
        this.KVHX = data().deepCopy(fields()[0].schema(), other.KVHX);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.KOMMUNE_KODE)) {
        this.KOMMUNE_KODE = data().deepCopy(fields()[1].schema(), other.KOMMUNE_KODE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.VEJ_KODE)) {
        this.VEJ_KODE = data().deepCopy(fields()[2].schema(), other.VEJ_KODE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.HUSNR)) {
        this.HUSNR = data().deepCopy(fields()[3].schema(), other.HUSNR);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ETAGE)) {
        this.ETAGE = data().deepCopy(fields()[4].schema(), other.ETAGE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SIDE_DOER)) {
        this.SIDE_DOER = data().deepCopy(fields()[5].schema(), other.SIDE_DOER);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.STEDNAVN)) {
        this.STEDNAVN = data().deepCopy(fields()[6].schema(), other.STEDNAVN);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.BYNAVN)) {
        this.BYNAVN = data().deepCopy(fields()[7].schema(), other.BYNAVN);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.SOGN)) {
        this.SOGN = data().deepCopy(fields()[8].schema(), other.SOGN);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.REGION)) {
        this.REGION = data().deepCopy(fields()[9].schema(), other.REGION);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.EJENDOM_BBR)) {
        this.EJENDOM_BBR = data().deepCopy(fields()[10].schema(), other.EJENDOM_BBR);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.EJENDOM_ESR)) {
        this.EJENDOM_ESR = data().deepCopy(fields()[11].schema(), other.EJENDOM_ESR);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ADGANG_OPRINDELSE)) {
        this.ADGANG_OPRINDELSE = data().deepCopy(fields()[12].schema(), other.ADGANG_OPRINDELSE);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ENHED_OPRINDELSE)) {
        this.ENHED_OPRINDELSE = data().deepCopy(fields()[13].schema(), other.ENHED_OPRINDELSE);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.BBR_BRUG)) {
        this.BBR_BRUG = data().deepCopy(fields()[14].schema(), other.BBR_BRUG);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.KOORDINAT_KVALITET)) {
        this.KOORDINAT_KVALITET = data().deepCopy(fields()[15].schema(), other.KOORDINAT_KVALITET);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.X_KOORDINAT)) {
        this.X_KOORDINAT = data().deepCopy(fields()[16].schema(), other.X_KOORDINAT);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.Y_KOORDINAT)) {
        this.Y_KOORDINAT = data().deepCopy(fields()[17].schema(), other.Y_KOORDINAT);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.OPRET_SBH)) {
        this.OPRET_SBH = data().deepCopy(fields()[18].schema(), other.OPRET_SBH);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.OPRET_TIMESTAMP)) {
        this.OPRET_TIMESTAMP = data().deepCopy(fields()[19].schema(), other.OPRET_TIMESTAMP);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RET_SBH)) {
        this.RET_SBH = data().deepCopy(fields()[20].schema(), other.RET_SBH);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.RET_TIMESTAMP)) {
        this.RET_TIMESTAMP = data().deepCopy(fields()[21].schema(), other.RET_TIMESTAMP);
        fieldSetFlags()[21] = true;
      }
    }

    /**
      * Gets the value of the 'KVHX' field.
      * @return The value.
      */
    public CharSequence getKVHX() {
      return KVHX;
    }

    /**
      * Sets the value of the 'KVHX' field.
      * @param value The value of 'KVHX'.
      * @return This builder.
      */
    public Builder setKVHX(CharSequence value) {
      validate(fields()[0], value);
      this.KVHX = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'KVHX' field has been set.
      * @return True if the 'KVHX' field has been set, false otherwise.
      */
    public boolean hasKVHX() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'KVHX' field.
      * @return This builder.
      */
    public Builder clearKVHX() {
      KVHX = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'KOMMUNE_KODE' field.
      * @return The value.
      */
    public Integer getKOMMUNEKODE() {
      return KOMMUNE_KODE;
    }

    /**
      * Sets the value of the 'KOMMUNE_KODE' field.
      * @param value The value of 'KOMMUNE_KODE'.
      * @return This builder.
      */
    public Builder setKOMMUNEKODE(Integer value) {
      validate(fields()[1], value);
      this.KOMMUNE_KODE = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'KOMMUNE_KODE' field has been set.
      * @return True if the 'KOMMUNE_KODE' field has been set, false otherwise.
      */
    public boolean hasKOMMUNEKODE() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'KOMMUNE_KODE' field.
      * @return This builder.
      */
    public Builder clearKOMMUNEKODE() {
      KOMMUNE_KODE = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'VEJ_KODE' field.
      * @return The value.
      */
    public Integer getVEJKODE() {
      return VEJ_KODE;
    }

    /**
      * Sets the value of the 'VEJ_KODE' field.
      * @param value The value of 'VEJ_KODE'.
      * @return This builder.
      */
    public Builder setVEJKODE(Integer value) {
      validate(fields()[2], value);
      this.VEJ_KODE = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'VEJ_KODE' field has been set.
      * @return True if the 'VEJ_KODE' field has been set, false otherwise.
      */
    public boolean hasVEJKODE() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'VEJ_KODE' field.
      * @return This builder.
      */
    public Builder clearVEJKODE() {
      VEJ_KODE = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'HUSNR' field.
      * @return The value.
      */
    public CharSequence getHUSNR() {
      return HUSNR;
    }

    /**
      * Sets the value of the 'HUSNR' field.
      * @param value The value of 'HUSNR'.
      * @return This builder.
      */
    public Builder setHUSNR(CharSequence value) {
      validate(fields()[3], value);
      this.HUSNR = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'HUSNR' field has been set.
      * @return True if the 'HUSNR' field has been set, false otherwise.
      */
    public boolean hasHUSNR() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'HUSNR' field.
      * @return This builder.
      */
    public Builder clearHUSNR() {
      HUSNR = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ETAGE' field.
      * @return The value.
      */
    public CharSequence getETAGE() {
      return ETAGE;
    }

    /**
      * Sets the value of the 'ETAGE' field.
      * @param value The value of 'ETAGE'.
      * @return This builder.
      */
    public Builder setETAGE(CharSequence value) {
      validate(fields()[4], value);
      this.ETAGE = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ETAGE' field has been set.
      * @return True if the 'ETAGE' field has been set, false otherwise.
      */
    public boolean hasETAGE() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ETAGE' field.
      * @return This builder.
      */
    public Builder clearETAGE() {
      ETAGE = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'SIDE_DOER' field.
      * @return The value.
      */
    public CharSequence getSIDEDOER() {
      return SIDE_DOER;
    }

    /**
      * Sets the value of the 'SIDE_DOER' field.
      * @param value The value of 'SIDE_DOER'.
      * @return This builder.
      */
    public Builder setSIDEDOER(CharSequence value) {
      validate(fields()[5], value);
      this.SIDE_DOER = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'SIDE_DOER' field has been set.
      * @return True if the 'SIDE_DOER' field has been set, false otherwise.
      */
    public boolean hasSIDEDOER() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'SIDE_DOER' field.
      * @return This builder.
      */
    public Builder clearSIDEDOER() {
      SIDE_DOER = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'STEDNAVN' field.
      * @return The value.
      */
    public CharSequence getSTEDNAVN() {
      return STEDNAVN;
    }

    /**
      * Sets the value of the 'STEDNAVN' field.
      * @param value The value of 'STEDNAVN'.
      * @return This builder.
      */
    public Builder setSTEDNAVN(CharSequence value) {
      validate(fields()[6], value);
      this.STEDNAVN = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'STEDNAVN' field has been set.
      * @return True if the 'STEDNAVN' field has been set, false otherwise.
      */
    public boolean hasSTEDNAVN() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'STEDNAVN' field.
      * @return This builder.
      */
    public Builder clearSTEDNAVN() {
      STEDNAVN = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'BYNAVN' field.
      * @return The value.
      */
    public CharSequence getBYNAVN() {
      return BYNAVN;
    }

    /**
      * Sets the value of the 'BYNAVN' field.
      * @param value The value of 'BYNAVN'.
      * @return This builder.
      */
    public Builder setBYNAVN(CharSequence value) {
      validate(fields()[7], value);
      this.BYNAVN = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'BYNAVN' field has been set.
      * @return True if the 'BYNAVN' field has been set, false otherwise.
      */
    public boolean hasBYNAVN() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'BYNAVN' field.
      * @return This builder.
      */
    public Builder clearBYNAVN() {
      BYNAVN = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'SOGN' field.
      * @return The value.
      */
    public CharSequence getSOGN() {
      return SOGN;
    }

    /**
      * Sets the value of the 'SOGN' field.
      * @param value The value of 'SOGN'.
      * @return This builder.
      */
    public Builder setSOGN(CharSequence value) {
      validate(fields()[8], value);
      this.SOGN = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'SOGN' field has been set.
      * @return True if the 'SOGN' field has been set, false otherwise.
      */
    public boolean hasSOGN() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'SOGN' field.
      * @return This builder.
      */
    public Builder clearSOGN() {
      SOGN = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'REGION' field.
      * @return The value.
      */
    public CharSequence getREGION() {
      return REGION;
    }

    /**
      * Sets the value of the 'REGION' field.
      * @param value The value of 'REGION'.
      * @return This builder.
      */
    public Builder setREGION(CharSequence value) {
      validate(fields()[9], value);
      this.REGION = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'REGION' field has been set.
      * @return True if the 'REGION' field has been set, false otherwise.
      */
    public boolean hasREGION() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'REGION' field.
      * @return This builder.
      */
    public Builder clearREGION() {
      REGION = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'EJENDOM_BBR' field.
      * @return The value.
      */
    public Integer getEJENDOMBBR() {
      return EJENDOM_BBR;
    }

    /**
      * Sets the value of the 'EJENDOM_BBR' field.
      * @param value The value of 'EJENDOM_BBR'.
      * @return This builder.
      */
    public Builder setEJENDOMBBR(Integer value) {
      validate(fields()[10], value);
      this.EJENDOM_BBR = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'EJENDOM_BBR' field has been set.
      * @return True if the 'EJENDOM_BBR' field has been set, false otherwise.
      */
    public boolean hasEJENDOMBBR() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'EJENDOM_BBR' field.
      * @return This builder.
      */
    public Builder clearEJENDOMBBR() {
      EJENDOM_BBR = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'EJENDOM_ESR' field.
      * @return The value.
      */
    public Integer getEJENDOMESR() {
      return EJENDOM_ESR;
    }

    /**
      * Sets the value of the 'EJENDOM_ESR' field.
      * @param value The value of 'EJENDOM_ESR'.
      * @return This builder.
      */
    public Builder setEJENDOMESR(Integer value) {
      validate(fields()[11], value);
      this.EJENDOM_ESR = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'EJENDOM_ESR' field has been set.
      * @return True if the 'EJENDOM_ESR' field has been set, false otherwise.
      */
    public boolean hasEJENDOMESR() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'EJENDOM_ESR' field.
      * @return This builder.
      */
    public Builder clearEJENDOMESR() {
      EJENDOM_ESR = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ADGANG_OPRINDELSE' field.
      * @return The value.
      */
    public Integer getADGANGOPRINDELSE() {
      return ADGANG_OPRINDELSE;
    }

    /**
      * Sets the value of the 'ADGANG_OPRINDELSE' field.
      * @param value The value of 'ADGANG_OPRINDELSE'.
      * @return This builder.
      */
    public Builder setADGANGOPRINDELSE(Integer value) {
      validate(fields()[12], value);
      this.ADGANG_OPRINDELSE = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ADGANG_OPRINDELSE' field has been set.
      * @return True if the 'ADGANG_OPRINDELSE' field has been set, false otherwise.
      */
    public boolean hasADGANGOPRINDELSE() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'ADGANG_OPRINDELSE' field.
      * @return This builder.
      */
    public Builder clearADGANGOPRINDELSE() {
      ADGANG_OPRINDELSE = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ENHED_OPRINDELSE' field.
      * @return The value.
      */
    public Integer getENHEDOPRINDELSE() {
      return ENHED_OPRINDELSE;
    }

    /**
      * Sets the value of the 'ENHED_OPRINDELSE' field.
      * @param value The value of 'ENHED_OPRINDELSE'.
      * @return This builder.
      */
    public Builder setENHEDOPRINDELSE(Integer value) {
      validate(fields()[13], value);
      this.ENHED_OPRINDELSE = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ENHED_OPRINDELSE' field has been set.
      * @return True if the 'ENHED_OPRINDELSE' field has been set, false otherwise.
      */
    public boolean hasENHEDOPRINDELSE() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'ENHED_OPRINDELSE' field.
      * @return This builder.
      */
    public Builder clearENHEDOPRINDELSE() {
      ENHED_OPRINDELSE = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'BBR_BRUG' field.
      * @return The value.
      */
    public Integer getBBRBRUG() {
      return BBR_BRUG;
    }

    /**
      * Sets the value of the 'BBR_BRUG' field.
      * @param value The value of 'BBR_BRUG'.
      * @return This builder.
      */
    public Builder setBBRBRUG(Integer value) {
      validate(fields()[14], value);
      this.BBR_BRUG = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'BBR_BRUG' field has been set.
      * @return True if the 'BBR_BRUG' field has been set, false otherwise.
      */
    public boolean hasBBRBRUG() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'BBR_BRUG' field.
      * @return This builder.
      */
    public Builder clearBBRBRUG() {
      BBR_BRUG = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'KOORDINAT_KVALITET' field.
      * @return The value.
      */
    public Integer getKOORDINATKVALITET() {
      return KOORDINAT_KVALITET;
    }

    /**
      * Sets the value of the 'KOORDINAT_KVALITET' field.
      * @param value The value of 'KOORDINAT_KVALITET'.
      * @return This builder.
      */
    public Builder setKOORDINATKVALITET(Integer value) {
      validate(fields()[15], value);
      this.KOORDINAT_KVALITET = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'KOORDINAT_KVALITET' field has been set.
      * @return True if the 'KOORDINAT_KVALITET' field has been set, false otherwise.
      */
    public boolean hasKOORDINATKVALITET() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'KOORDINAT_KVALITET' field.
      * @return This builder.
      */
    public Builder clearKOORDINATKVALITET() {
      KOORDINAT_KVALITET = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'X_KOORDINAT' field.
      * @return The value.
      */
    public Integer getXKOORDINAT() {
      return X_KOORDINAT;
    }

    /**
      * Sets the value of the 'X_KOORDINAT' field.
      * @param value The value of 'X_KOORDINAT'.
      * @return This builder.
      */
    public Builder setXKOORDINAT(Integer value) {
      validate(fields()[16], value);
      this.X_KOORDINAT = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'X_KOORDINAT' field has been set.
      * @return True if the 'X_KOORDINAT' field has been set, false otherwise.
      */
    public boolean hasXKOORDINAT() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'X_KOORDINAT' field.
      * @return This builder.
      */
    public Builder clearXKOORDINAT() {
      X_KOORDINAT = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'Y_KOORDINAT' field.
      * @return The value.
      */
    public Integer getYKOORDINAT() {
      return Y_KOORDINAT;
    }

    /**
      * Sets the value of the 'Y_KOORDINAT' field.
      * @param value The value of 'Y_KOORDINAT'.
      * @return This builder.
      */
    public Builder setYKOORDINAT(Integer value) {
      validate(fields()[17], value);
      this.Y_KOORDINAT = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'Y_KOORDINAT' field has been set.
      * @return True if the 'Y_KOORDINAT' field has been set, false otherwise.
      */
    public boolean hasYKOORDINAT() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'Y_KOORDINAT' field.
      * @return This builder.
      */
    public Builder clearYKOORDINAT() {
      Y_KOORDINAT = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'OPRET_SBH' field.
      * @return The value.
      */
    public CharSequence getOPRETSBH() {
      return OPRET_SBH;
    }

    /**
      * Sets the value of the 'OPRET_SBH' field.
      * @param value The value of 'OPRET_SBH'.
      * @return This builder.
      */
    public Builder setOPRETSBH(CharSequence value) {
      validate(fields()[18], value);
      this.OPRET_SBH = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'OPRET_SBH' field has been set.
      * @return True if the 'OPRET_SBH' field has been set, false otherwise.
      */
    public boolean hasOPRETSBH() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'OPRET_SBH' field.
      * @return This builder.
      */
    public Builder clearOPRETSBH() {
      OPRET_SBH = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'OPRET_TIMESTAMP' field.
      * @return The value.
      */
    public CharSequence getOPRETTIMESTAMP() {
      return OPRET_TIMESTAMP;
    }

    /**
      * Sets the value of the 'OPRET_TIMESTAMP' field.
      * @param value The value of 'OPRET_TIMESTAMP'.
      * @return This builder.
      */
    public Builder setOPRETTIMESTAMP(CharSequence value) {
      validate(fields()[19], value);
      this.OPRET_TIMESTAMP = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'OPRET_TIMESTAMP' field has been set.
      * @return True if the 'OPRET_TIMESTAMP' field has been set, false otherwise.
      */
    public boolean hasOPRETTIMESTAMP() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'OPRET_TIMESTAMP' field.
      * @return This builder.
      */
    public Builder clearOPRETTIMESTAMP() {
      OPRET_TIMESTAMP = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'RET_SBH' field.
      * @return The value.
      */
    public CharSequence getRETSBH() {
      return RET_SBH;
    }

    /**
      * Sets the value of the 'RET_SBH' field.
      * @param value The value of 'RET_SBH'.
      * @return This builder.
      */
    public Builder setRETSBH(CharSequence value) {
      validate(fields()[20], value);
      this.RET_SBH = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'RET_SBH' field has been set.
      * @return True if the 'RET_SBH' field has been set, false otherwise.
      */
    public boolean hasRETSBH() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'RET_SBH' field.
      * @return This builder.
      */
    public Builder clearRETSBH() {
      RET_SBH = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'RET_TIMESTAMP' field.
      * @return The value.
      */
    public CharSequence getRETTIMESTAMP() {
      return RET_TIMESTAMP;
    }

    /**
      * Sets the value of the 'RET_TIMESTAMP' field.
      * @param value The value of 'RET_TIMESTAMP'.
      * @return This builder.
      */
    public Builder setRETTIMESTAMP(CharSequence value) {
      validate(fields()[21], value);
      this.RET_TIMESTAMP = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'RET_TIMESTAMP' field has been set.
      * @return True if the 'RET_TIMESTAMP' field has been set, false otherwise.
      */
    public boolean hasRETTIMESTAMP() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'RET_TIMESTAMP' field.
      * @return This builder.
      */
    public Builder clearRETTIMESTAMP() {
      RET_TIMESTAMP = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public Data build() {
      try {
        Data record = new Data();
        record.KVHX = fieldSetFlags()[0] ? this.KVHX : (CharSequence) defaultValue(fields()[0]);
        record.KOMMUNE_KODE = fieldSetFlags()[1] ? this.KOMMUNE_KODE : (Integer) defaultValue(fields()[1]);
        record.VEJ_KODE = fieldSetFlags()[2] ? this.VEJ_KODE : (Integer) defaultValue(fields()[2]);
        record.HUSNR = fieldSetFlags()[3] ? this.HUSNR : (CharSequence) defaultValue(fields()[3]);
        record.ETAGE = fieldSetFlags()[4] ? this.ETAGE : (CharSequence) defaultValue(fields()[4]);
        record.SIDE_DOER = fieldSetFlags()[5] ? this.SIDE_DOER : (CharSequence) defaultValue(fields()[5]);
        record.STEDNAVN = fieldSetFlags()[6] ? this.STEDNAVN : (CharSequence) defaultValue(fields()[6]);
        record.BYNAVN = fieldSetFlags()[7] ? this.BYNAVN : (CharSequence) defaultValue(fields()[7]);
        record.SOGN = fieldSetFlags()[8] ? this.SOGN : (CharSequence) defaultValue(fields()[8]);
        record.REGION = fieldSetFlags()[9] ? this.REGION : (CharSequence) defaultValue(fields()[9]);
        record.EJENDOM_BBR = fieldSetFlags()[10] ? this.EJENDOM_BBR : (Integer) defaultValue(fields()[10]);
        record.EJENDOM_ESR = fieldSetFlags()[11] ? this.EJENDOM_ESR : (Integer) defaultValue(fields()[11]);
        record.ADGANG_OPRINDELSE = fieldSetFlags()[12] ? this.ADGANG_OPRINDELSE : (Integer) defaultValue(fields()[12]);
        record.ENHED_OPRINDELSE = fieldSetFlags()[13] ? this.ENHED_OPRINDELSE : (Integer) defaultValue(fields()[13]);
        record.BBR_BRUG = fieldSetFlags()[14] ? this.BBR_BRUG : (Integer) defaultValue(fields()[14]);
        record.KOORDINAT_KVALITET = fieldSetFlags()[15] ? this.KOORDINAT_KVALITET : (Integer) defaultValue(fields()[15]);
        record.X_KOORDINAT = fieldSetFlags()[16] ? this.X_KOORDINAT : (Integer) defaultValue(fields()[16]);
        record.Y_KOORDINAT = fieldSetFlags()[17] ? this.Y_KOORDINAT : (Integer) defaultValue(fields()[17]);
        record.OPRET_SBH = fieldSetFlags()[18] ? this.OPRET_SBH : (CharSequence) defaultValue(fields()[18]);
        record.OPRET_TIMESTAMP = fieldSetFlags()[19] ? this.OPRET_TIMESTAMP : (CharSequence) defaultValue(fields()[19]);
        record.RET_SBH = fieldSetFlags()[20] ? this.RET_SBH : (CharSequence) defaultValue(fields()[20]);
        record.RET_TIMESTAMP = fieldSetFlags()[21] ? this.RET_TIMESTAMP : (CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
