package wikiedits; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DataOrg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1594882531013710657L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Data\",\"fields\":[{\"name\":\"FF_NR\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"FORNAVN\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"EFTERNAVN\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_NR\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"M_K_KODE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"FOEDSELSDATO\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"FOEDSDAT_AENDR_DOK\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PERSON_STATUS_DATO\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PERSON_STATUS\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"PERSON_STATUS_DOK\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_DATA_FORSKEL\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_ADR_OPD\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_FORNAVN_OPD\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_EFTERNAVN_OPD\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_NR_OPLYST_KODE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CPR_NR_AENDR_DOK\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"KALDE_FORNAVN_MRK\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"TJM_KODE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STILLING_DATO\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"RET_SBH\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"RET_TIMESTAMP\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"STILLING\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence FF_NR;
  @Deprecated public CharSequence FORNAVN;
  @Deprecated public CharSequence EFTERNAVN;
  @Deprecated public CharSequence CPR_NR;
  @Deprecated public CharSequence M_K_KODE;
  @Deprecated public CharSequence FOEDSELSDATO;
  @Deprecated public CharSequence FOEDSDAT_AENDR_DOK;
  @Deprecated public CharSequence PERSON_STATUS_DATO;
  @Deprecated public CharSequence PERSON_STATUS;
  @Deprecated public CharSequence PERSON_STATUS_DOK;
  @Deprecated public CharSequence CPR_DATA_FORSKEL;
  @Deprecated public CharSequence CPR_ADR_OPD;
  @Deprecated public CharSequence CPR_FORNAVN_OPD;
  @Deprecated public CharSequence CPR_EFTERNAVN_OPD;
  @Deprecated public CharSequence CPR_NR_OPLYST_KODE;
  @Deprecated public CharSequence CPR_NR_AENDR_DOK;
  @Deprecated public CharSequence KALDE_FORNAVN_MRK;
  @Deprecated public CharSequence TJM_KODE;
  @Deprecated public CharSequence STILLING_DATO;
  @Deprecated public CharSequence RET_SBH;
  @Deprecated public CharSequence RET_TIMESTAMP;
  @Deprecated public CharSequence STILLING;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataOrg() {}

  /**
   * All-args constructor.
   * @param FF_NR The new value for FF_NR
   * @param FORNAVN The new value for FORNAVN
   * @param EFTERNAVN The new value for EFTERNAVN
   * @param CPR_NR The new value for CPR_NR
   * @param M_K_KODE The new value for M_K_KODE
   * @param FOEDSELSDATO The new value for FOEDSELSDATO
   * @param FOEDSDAT_AENDR_DOK The new value for FOEDSDAT_AENDR_DOK
   * @param PERSON_STATUS_DATO The new value for PERSON_STATUS_DATO
   * @param PERSON_STATUS The new value for PERSON_STATUS
   * @param PERSON_STATUS_DOK The new value for PERSON_STATUS_DOK
   * @param CPR_DATA_FORSKEL The new value for CPR_DATA_FORSKEL
   * @param CPR_ADR_OPD The new value for CPR_ADR_OPD
   * @param CPR_FORNAVN_OPD The new value for CPR_FORNAVN_OPD
   * @param CPR_EFTERNAVN_OPD The new value for CPR_EFTERNAVN_OPD
   * @param CPR_NR_OPLYST_KODE The new value for CPR_NR_OPLYST_KODE
   * @param CPR_NR_AENDR_DOK The new value for CPR_NR_AENDR_DOK
   * @param KALDE_FORNAVN_MRK The new value for KALDE_FORNAVN_MRK
   * @param TJM_KODE The new value for TJM_KODE
   * @param STILLING_DATO The new value for STILLING_DATO
   * @param RET_SBH The new value for RET_SBH
   * @param RET_TIMESTAMP The new value for RET_TIMESTAMP
   * @param STILLING The new value for STILLING
   */
  public DataOrg(CharSequence FF_NR, CharSequence FORNAVN, CharSequence EFTERNAVN, CharSequence CPR_NR, CharSequence M_K_KODE, CharSequence FOEDSELSDATO, CharSequence FOEDSDAT_AENDR_DOK, CharSequence PERSON_STATUS_DATO, CharSequence PERSON_STATUS, CharSequence PERSON_STATUS_DOK, CharSequence CPR_DATA_FORSKEL, CharSequence CPR_ADR_OPD, CharSequence CPR_FORNAVN_OPD, CharSequence CPR_EFTERNAVN_OPD, CharSequence CPR_NR_OPLYST_KODE, CharSequence CPR_NR_AENDR_DOK, CharSequence KALDE_FORNAVN_MRK, CharSequence TJM_KODE, CharSequence STILLING_DATO, CharSequence RET_SBH, CharSequence RET_TIMESTAMP, CharSequence STILLING) {
    this.FF_NR = FF_NR;
    this.FORNAVN = FORNAVN;
    this.EFTERNAVN = EFTERNAVN;
    this.CPR_NR = CPR_NR;
    this.M_K_KODE = M_K_KODE;
    this.FOEDSELSDATO = FOEDSELSDATO;
    this.FOEDSDAT_AENDR_DOK = FOEDSDAT_AENDR_DOK;
    this.PERSON_STATUS_DATO = PERSON_STATUS_DATO;
    this.PERSON_STATUS = PERSON_STATUS;
    this.PERSON_STATUS_DOK = PERSON_STATUS_DOK;
    this.CPR_DATA_FORSKEL = CPR_DATA_FORSKEL;
    this.CPR_ADR_OPD = CPR_ADR_OPD;
    this.CPR_FORNAVN_OPD = CPR_FORNAVN_OPD;
    this.CPR_EFTERNAVN_OPD = CPR_EFTERNAVN_OPD;
    this.CPR_NR_OPLYST_KODE = CPR_NR_OPLYST_KODE;
    this.CPR_NR_AENDR_DOK = CPR_NR_AENDR_DOK;
    this.KALDE_FORNAVN_MRK = KALDE_FORNAVN_MRK;
    this.TJM_KODE = TJM_KODE;
    this.STILLING_DATO = STILLING_DATO;
    this.RET_SBH = RET_SBH;
    this.RET_TIMESTAMP = RET_TIMESTAMP;
    this.STILLING = STILLING;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return FF_NR;
    case 1: return FORNAVN;
    case 2: return EFTERNAVN;
    case 3: return CPR_NR;
    case 4: return M_K_KODE;
    case 5: return FOEDSELSDATO;
    case 6: return FOEDSDAT_AENDR_DOK;
    case 7: return PERSON_STATUS_DATO;
    case 8: return PERSON_STATUS;
    case 9: return PERSON_STATUS_DOK;
    case 10: return CPR_DATA_FORSKEL;
    case 11: return CPR_ADR_OPD;
    case 12: return CPR_FORNAVN_OPD;
    case 13: return CPR_EFTERNAVN_OPD;
    case 14: return CPR_NR_OPLYST_KODE;
    case 15: return CPR_NR_AENDR_DOK;
    case 16: return KALDE_FORNAVN_MRK;
    case 17: return TJM_KODE;
    case 18: return STILLING_DATO;
    case 19: return RET_SBH;
    case 20: return RET_TIMESTAMP;
    case 21: return STILLING;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: FF_NR = (CharSequence)value$; break;
    case 1: FORNAVN = (CharSequence)value$; break;
    case 2: EFTERNAVN = (CharSequence)value$; break;
    case 3: CPR_NR = (CharSequence)value$; break;
    case 4: M_K_KODE = (CharSequence)value$; break;
    case 5: FOEDSELSDATO = (CharSequence)value$; break;
    case 6: FOEDSDAT_AENDR_DOK = (CharSequence)value$; break;
    case 7: PERSON_STATUS_DATO = (CharSequence)value$; break;
    case 8: PERSON_STATUS = (CharSequence)value$; break;
    case 9: PERSON_STATUS_DOK = (CharSequence)value$; break;
    case 10: CPR_DATA_FORSKEL = (CharSequence)value$; break;
    case 11: CPR_ADR_OPD = (CharSequence)value$; break;
    case 12: CPR_FORNAVN_OPD = (CharSequence)value$; break;
    case 13: CPR_EFTERNAVN_OPD = (CharSequence)value$; break;
    case 14: CPR_NR_OPLYST_KODE = (CharSequence)value$; break;
    case 15: CPR_NR_AENDR_DOK = (CharSequence)value$; break;
    case 16: KALDE_FORNAVN_MRK = (CharSequence)value$; break;
    case 17: TJM_KODE = (CharSequence)value$; break;
    case 18: STILLING_DATO = (CharSequence)value$; break;
    case 19: RET_SBH = (CharSequence)value$; break;
    case 20: RET_TIMESTAMP = (CharSequence)value$; break;
    case 21: STILLING = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'FF_NR' field.
   * @return The value of the 'FF_NR' field.
   */
  public CharSequence getFFNR() {
    return FF_NR;
  }

  /**
   * Sets the value of the 'FF_NR' field.
   * @param value the value to set.
   */
  public void setFFNR(CharSequence value) {
    this.FF_NR = value;
  }

  /**
   * Gets the value of the 'FORNAVN' field.
   * @return The value of the 'FORNAVN' field.
   */
  public CharSequence getFORNAVN() {
    return FORNAVN;
  }

  /**
   * Sets the value of the 'FORNAVN' field.
   * @param value the value to set.
   */
  public void setFORNAVN(CharSequence value) {
    this.FORNAVN = value;
  }

  /**
   * Gets the value of the 'EFTERNAVN' field.
   * @return The value of the 'EFTERNAVN' field.
   */
  public CharSequence getEFTERNAVN() {
    return EFTERNAVN;
  }

  /**
   * Sets the value of the 'EFTERNAVN' field.
   * @param value the value to set.
   */
  public void setEFTERNAVN(CharSequence value) {
    this.EFTERNAVN = value;
  }

  /**
   * Gets the value of the 'CPR_NR' field.
   * @return The value of the 'CPR_NR' field.
   */
  public CharSequence getCPRNR() {
    return CPR_NR;
  }

  /**
   * Sets the value of the 'CPR_NR' field.
   * @param value the value to set.
   */
  public void setCPRNR(CharSequence value) {
    this.CPR_NR = value;
  }

  /**
   * Gets the value of the 'M_K_KODE' field.
   * @return The value of the 'M_K_KODE' field.
   */
  public CharSequence getMKKODE() {
    return M_K_KODE;
  }

  /**
   * Sets the value of the 'M_K_KODE' field.
   * @param value the value to set.
   */
  public void setMKKODE(CharSequence value) {
    this.M_K_KODE = value;
  }

  /**
   * Gets the value of the 'FOEDSELSDATO' field.
   * @return The value of the 'FOEDSELSDATO' field.
   */
  public CharSequence getFOEDSELSDATO() {
    return FOEDSELSDATO;
  }

  /**
   * Sets the value of the 'FOEDSELSDATO' field.
   * @param value the value to set.
   */
  public void setFOEDSELSDATO(CharSequence value) {
    this.FOEDSELSDATO = value;
  }

  /**
   * Gets the value of the 'FOEDSDAT_AENDR_DOK' field.
   * @return The value of the 'FOEDSDAT_AENDR_DOK' field.
   */
  public CharSequence getFOEDSDATAENDRDOK() {
    return FOEDSDAT_AENDR_DOK;
  }

  /**
   * Sets the value of the 'FOEDSDAT_AENDR_DOK' field.
   * @param value the value to set.
   */
  public void setFOEDSDATAENDRDOK(CharSequence value) {
    this.FOEDSDAT_AENDR_DOK = value;
  }

  /**
   * Gets the value of the 'PERSON_STATUS_DATO' field.
   * @return The value of the 'PERSON_STATUS_DATO' field.
   */
  public CharSequence getPERSONSTATUSDATO() {
    return PERSON_STATUS_DATO;
  }

  /**
   * Sets the value of the 'PERSON_STATUS_DATO' field.
   * @param value the value to set.
   */
  public void setPERSONSTATUSDATO(CharSequence value) {
    this.PERSON_STATUS_DATO = value;
  }

  /**
   * Gets the value of the 'PERSON_STATUS' field.
   * @return The value of the 'PERSON_STATUS' field.
   */
  public CharSequence getPERSONSTATUS() {
    return PERSON_STATUS;
  }

  /**
   * Sets the value of the 'PERSON_STATUS' field.
   * @param value the value to set.
   */
  public void setPERSONSTATUS(CharSequence value) {
    this.PERSON_STATUS = value;
  }

  /**
   * Gets the value of the 'PERSON_STATUS_DOK' field.
   * @return The value of the 'PERSON_STATUS_DOK' field.
   */
  public CharSequence getPERSONSTATUSDOK() {
    return PERSON_STATUS_DOK;
  }

  /**
   * Sets the value of the 'PERSON_STATUS_DOK' field.
   * @param value the value to set.
   */
  public void setPERSONSTATUSDOK(CharSequence value) {
    this.PERSON_STATUS_DOK = value;
  }

  /**
   * Gets the value of the 'CPR_DATA_FORSKEL' field.
   * @return The value of the 'CPR_DATA_FORSKEL' field.
   */
  public CharSequence getCPRDATAFORSKEL() {
    return CPR_DATA_FORSKEL;
  }

  /**
   * Sets the value of the 'CPR_DATA_FORSKEL' field.
   * @param value the value to set.
   */
  public void setCPRDATAFORSKEL(CharSequence value) {
    this.CPR_DATA_FORSKEL = value;
  }

  /**
   * Gets the value of the 'CPR_ADR_OPD' field.
   * @return The value of the 'CPR_ADR_OPD' field.
   */
  public CharSequence getCPRADROPD() {
    return CPR_ADR_OPD;
  }

  /**
   * Sets the value of the 'CPR_ADR_OPD' field.
   * @param value the value to set.
   */
  public void setCPRADROPD(CharSequence value) {
    this.CPR_ADR_OPD = value;
  }

  /**
   * Gets the value of the 'CPR_FORNAVN_OPD' field.
   * @return The value of the 'CPR_FORNAVN_OPD' field.
   */
  public CharSequence getCPRFORNAVNOPD() {
    return CPR_FORNAVN_OPD;
  }

  /**
   * Sets the value of the 'CPR_FORNAVN_OPD' field.
   * @param value the value to set.
   */
  public void setCPRFORNAVNOPD(CharSequence value) {
    this.CPR_FORNAVN_OPD = value;
  }

  /**
   * Gets the value of the 'CPR_EFTERNAVN_OPD' field.
   * @return The value of the 'CPR_EFTERNAVN_OPD' field.
   */
  public CharSequence getCPREFTERNAVNOPD() {
    return CPR_EFTERNAVN_OPD;
  }

  /**
   * Sets the value of the 'CPR_EFTERNAVN_OPD' field.
   * @param value the value to set.
   */
  public void setCPREFTERNAVNOPD(CharSequence value) {
    this.CPR_EFTERNAVN_OPD = value;
  }

  /**
   * Gets the value of the 'CPR_NR_OPLYST_KODE' field.
   * @return The value of the 'CPR_NR_OPLYST_KODE' field.
   */
  public CharSequence getCPRNROPLYSTKODE() {
    return CPR_NR_OPLYST_KODE;
  }

  /**
   * Sets the value of the 'CPR_NR_OPLYST_KODE' field.
   * @param value the value to set.
   */
  public void setCPRNROPLYSTKODE(CharSequence value) {
    this.CPR_NR_OPLYST_KODE = value;
  }

  /**
   * Gets the value of the 'CPR_NR_AENDR_DOK' field.
   * @return The value of the 'CPR_NR_AENDR_DOK' field.
   */
  public CharSequence getCPRNRAENDRDOK() {
    return CPR_NR_AENDR_DOK;
  }

  /**
   * Sets the value of the 'CPR_NR_AENDR_DOK' field.
   * @param value the value to set.
   */
  public void setCPRNRAENDRDOK(CharSequence value) {
    this.CPR_NR_AENDR_DOK = value;
  }

  /**
   * Gets the value of the 'KALDE_FORNAVN_MRK' field.
   * @return The value of the 'KALDE_FORNAVN_MRK' field.
   */
  public CharSequence getKALDEFORNAVNMRK() {
    return KALDE_FORNAVN_MRK;
  }

  /**
   * Sets the value of the 'KALDE_FORNAVN_MRK' field.
   * @param value the value to set.
   */
  public void setKALDEFORNAVNMRK(CharSequence value) {
    this.KALDE_FORNAVN_MRK = value;
  }

  /**
   * Gets the value of the 'TJM_KODE' field.
   * @return The value of the 'TJM_KODE' field.
   */
  public CharSequence getTJMKODE() {
    return TJM_KODE;
  }

  /**
   * Sets the value of the 'TJM_KODE' field.
   * @param value the value to set.
   */
  public void setTJMKODE(CharSequence value) {
    this.TJM_KODE = value;
  }

  /**
   * Gets the value of the 'STILLING_DATO' field.
   * @return The value of the 'STILLING_DATO' field.
   */
  public CharSequence getSTILLINGDATO() {
    return STILLING_DATO;
  }

  /**
   * Sets the value of the 'STILLING_DATO' field.
   * @param value the value to set.
   */
  public void setSTILLINGDATO(CharSequence value) {
    this.STILLING_DATO = value;
  }

  /**
   * Gets the value of the 'RET_SBH' field.
   * @return The value of the 'RET_SBH' field.
   */
  public CharSequence getRETSBH() {
    return RET_SBH;
  }

  /**
   * Sets the value of the 'RET_SBH' field.
   * @param value the value to set.
   */
  public void setRETSBH(CharSequence value) {
    this.RET_SBH = value;
  }

  /**
   * Gets the value of the 'RET_TIMESTAMP' field.
   * @return The value of the 'RET_TIMESTAMP' field.
   */
  public CharSequence getRETTIMESTAMP() {
    return RET_TIMESTAMP;
  }

  /**
   * Sets the value of the 'RET_TIMESTAMP' field.
   * @param value the value to set.
   */
  public void setRETTIMESTAMP(CharSequence value) {
    this.RET_TIMESTAMP = value;
  }

  /**
   * Gets the value of the 'STILLING' field.
   * @return The value of the 'STILLING' field.
   */
  public CharSequence getSTILLING() {
    return STILLING;
  }

  /**
   * Sets the value of the 'STILLING' field.
   * @param value the value to set.
   */
  public void setSTILLING(CharSequence value) {
    this.STILLING = value;
  }

  /**
   * Creates a new Data RecordBuilder.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Data instance.
   * @param other The existing instance to copy.
   * @return A new Data RecordBuilder
   */
  public static Builder newBuilder(DataOrg other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Data instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataOrg>
    implements org.apache.avro.data.RecordBuilder<DataOrg> {

    private CharSequence FF_NR;
    private CharSequence FORNAVN;
    private CharSequence EFTERNAVN;
    private CharSequence CPR_NR;
    private CharSequence M_K_KODE;
    private CharSequence FOEDSELSDATO;
    private CharSequence FOEDSDAT_AENDR_DOK;
    private CharSequence PERSON_STATUS_DATO;
    private CharSequence PERSON_STATUS;
    private CharSequence PERSON_STATUS_DOK;
    private CharSequence CPR_DATA_FORSKEL;
    private CharSequence CPR_ADR_OPD;
    private CharSequence CPR_FORNAVN_OPD;
    private CharSequence CPR_EFTERNAVN_OPD;
    private CharSequence CPR_NR_OPLYST_KODE;
    private CharSequence CPR_NR_AENDR_DOK;
    private CharSequence KALDE_FORNAVN_MRK;
    private CharSequence TJM_KODE;
    private CharSequence STILLING_DATO;
    private CharSequence RET_SBH;
    private CharSequence RET_TIMESTAMP;
    private CharSequence STILLING;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.FF_NR)) {
        this.FF_NR = data().deepCopy(fields()[0].schema(), other.FF_NR);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.FORNAVN)) {
        this.FORNAVN = data().deepCopy(fields()[1].schema(), other.FORNAVN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EFTERNAVN)) {
        this.EFTERNAVN = data().deepCopy(fields()[2].schema(), other.EFTERNAVN);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CPR_NR)) {
        this.CPR_NR = data().deepCopy(fields()[3].schema(), other.CPR_NR);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.M_K_KODE)) {
        this.M_K_KODE = data().deepCopy(fields()[4].schema(), other.M_K_KODE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FOEDSELSDATO)) {
        this.FOEDSELSDATO = data().deepCopy(fields()[5].schema(), other.FOEDSELSDATO);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.FOEDSDAT_AENDR_DOK)) {
        this.FOEDSDAT_AENDR_DOK = data().deepCopy(fields()[6].schema(), other.FOEDSDAT_AENDR_DOK);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PERSON_STATUS_DATO)) {
        this.PERSON_STATUS_DATO = data().deepCopy(fields()[7].schema(), other.PERSON_STATUS_DATO);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.PERSON_STATUS)) {
        this.PERSON_STATUS = data().deepCopy(fields()[8].schema(), other.PERSON_STATUS);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.PERSON_STATUS_DOK)) {
        this.PERSON_STATUS_DOK = data().deepCopy(fields()[9].schema(), other.PERSON_STATUS_DOK);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.CPR_DATA_FORSKEL)) {
        this.CPR_DATA_FORSKEL = data().deepCopy(fields()[10].schema(), other.CPR_DATA_FORSKEL);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CPR_ADR_OPD)) {
        this.CPR_ADR_OPD = data().deepCopy(fields()[11].schema(), other.CPR_ADR_OPD);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CPR_FORNAVN_OPD)) {
        this.CPR_FORNAVN_OPD = data().deepCopy(fields()[12].schema(), other.CPR_FORNAVN_OPD);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.CPR_EFTERNAVN_OPD)) {
        this.CPR_EFTERNAVN_OPD = data().deepCopy(fields()[13].schema(), other.CPR_EFTERNAVN_OPD);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CPR_NR_OPLYST_KODE)) {
        this.CPR_NR_OPLYST_KODE = data().deepCopy(fields()[14].schema(), other.CPR_NR_OPLYST_KODE);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.CPR_NR_AENDR_DOK)) {
        this.CPR_NR_AENDR_DOK = data().deepCopy(fields()[15].schema(), other.CPR_NR_AENDR_DOK);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.KALDE_FORNAVN_MRK)) {
        this.KALDE_FORNAVN_MRK = data().deepCopy(fields()[16].schema(), other.KALDE_FORNAVN_MRK);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.TJM_KODE)) {
        this.TJM_KODE = data().deepCopy(fields()[17].schema(), other.TJM_KODE);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.STILLING_DATO)) {
        this.STILLING_DATO = data().deepCopy(fields()[18].schema(), other.STILLING_DATO);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.RET_SBH)) {
        this.RET_SBH = data().deepCopy(fields()[19].schema(), other.RET_SBH);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RET_TIMESTAMP)) {
        this.RET_TIMESTAMP = data().deepCopy(fields()[20].schema(), other.RET_TIMESTAMP);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.STILLING)) {
        this.STILLING = data().deepCopy(fields()[21].schema(), other.STILLING);
        fieldSetFlags()[21] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Data instance
     * @param other The existing instance to copy.
     */
    private Builder(DataOrg other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.FF_NR)) {
        this.FF_NR = data().deepCopy(fields()[0].schema(), other.FF_NR);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.FORNAVN)) {
        this.FORNAVN = data().deepCopy(fields()[1].schema(), other.FORNAVN);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.EFTERNAVN)) {
        this.EFTERNAVN = data().deepCopy(fields()[2].schema(), other.EFTERNAVN);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CPR_NR)) {
        this.CPR_NR = data().deepCopy(fields()[3].schema(), other.CPR_NR);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.M_K_KODE)) {
        this.M_K_KODE = data().deepCopy(fields()[4].schema(), other.M_K_KODE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FOEDSELSDATO)) {
        this.FOEDSELSDATO = data().deepCopy(fields()[5].schema(), other.FOEDSELSDATO);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.FOEDSDAT_AENDR_DOK)) {
        this.FOEDSDAT_AENDR_DOK = data().deepCopy(fields()[6].schema(), other.FOEDSDAT_AENDR_DOK);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.PERSON_STATUS_DATO)) {
        this.PERSON_STATUS_DATO = data().deepCopy(fields()[7].schema(), other.PERSON_STATUS_DATO);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.PERSON_STATUS)) {
        this.PERSON_STATUS = data().deepCopy(fields()[8].schema(), other.PERSON_STATUS);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.PERSON_STATUS_DOK)) {
        this.PERSON_STATUS_DOK = data().deepCopy(fields()[9].schema(), other.PERSON_STATUS_DOK);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.CPR_DATA_FORSKEL)) {
        this.CPR_DATA_FORSKEL = data().deepCopy(fields()[10].schema(), other.CPR_DATA_FORSKEL);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CPR_ADR_OPD)) {
        this.CPR_ADR_OPD = data().deepCopy(fields()[11].schema(), other.CPR_ADR_OPD);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CPR_FORNAVN_OPD)) {
        this.CPR_FORNAVN_OPD = data().deepCopy(fields()[12].schema(), other.CPR_FORNAVN_OPD);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.CPR_EFTERNAVN_OPD)) {
        this.CPR_EFTERNAVN_OPD = data().deepCopy(fields()[13].schema(), other.CPR_EFTERNAVN_OPD);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CPR_NR_OPLYST_KODE)) {
        this.CPR_NR_OPLYST_KODE = data().deepCopy(fields()[14].schema(), other.CPR_NR_OPLYST_KODE);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.CPR_NR_AENDR_DOK)) {
        this.CPR_NR_AENDR_DOK = data().deepCopy(fields()[15].schema(), other.CPR_NR_AENDR_DOK);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.KALDE_FORNAVN_MRK)) {
        this.KALDE_FORNAVN_MRK = data().deepCopy(fields()[16].schema(), other.KALDE_FORNAVN_MRK);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.TJM_KODE)) {
        this.TJM_KODE = data().deepCopy(fields()[17].schema(), other.TJM_KODE);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.STILLING_DATO)) {
        this.STILLING_DATO = data().deepCopy(fields()[18].schema(), other.STILLING_DATO);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.RET_SBH)) {
        this.RET_SBH = data().deepCopy(fields()[19].schema(), other.RET_SBH);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.RET_TIMESTAMP)) {
        this.RET_TIMESTAMP = data().deepCopy(fields()[20].schema(), other.RET_TIMESTAMP);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.STILLING)) {
        this.STILLING = data().deepCopy(fields()[21].schema(), other.STILLING);
        fieldSetFlags()[21] = true;
      }
    }

    /**
      * Gets the value of the 'FF_NR' field.
      * @return The value.
      */
    public CharSequence getFFNR() {
      return FF_NR;
    }

    /**
      * Sets the value of the 'FF_NR' field.
      * @param value The value of 'FF_NR'.
      * @return This builder.
      */
    public Builder setFFNR(CharSequence value) {
      validate(fields()[0], value);
      this.FF_NR = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'FF_NR' field has been set.
      * @return True if the 'FF_NR' field has been set, false otherwise.
      */
    public boolean hasFFNR() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'FF_NR' field.
      * @return This builder.
      */
    public Builder clearFFNR() {
      FF_NR = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'FORNAVN' field.
      * @return The value.
      */
    public CharSequence getFORNAVN() {
      return FORNAVN;
    }

    /**
      * Sets the value of the 'FORNAVN' field.
      * @param value The value of 'FORNAVN'.
      * @return This builder.
      */
    public Builder setFORNAVN(CharSequence value) {
      validate(fields()[1], value);
      this.FORNAVN = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'FORNAVN' field has been set.
      * @return True if the 'FORNAVN' field has been set, false otherwise.
      */
    public boolean hasFORNAVN() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'FORNAVN' field.
      * @return This builder.
      */
    public Builder clearFORNAVN() {
      FORNAVN = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'EFTERNAVN' field.
      * @return The value.
      */
    public CharSequence getEFTERNAVN() {
      return EFTERNAVN;
    }

    /**
      * Sets the value of the 'EFTERNAVN' field.
      * @param value The value of 'EFTERNAVN'.
      * @return This builder.
      */
    public Builder setEFTERNAVN(CharSequence value) {
      validate(fields()[2], value);
      this.EFTERNAVN = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'EFTERNAVN' field has been set.
      * @return True if the 'EFTERNAVN' field has been set, false otherwise.
      */
    public boolean hasEFTERNAVN() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'EFTERNAVN' field.
      * @return This builder.
      */
    public Builder clearEFTERNAVN() {
      EFTERNAVN = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_NR' field.
      * @return The value.
      */
    public CharSequence getCPRNR() {
      return CPR_NR;
    }

    /**
      * Sets the value of the 'CPR_NR' field.
      * @param value The value of 'CPR_NR'.
      * @return This builder.
      */
    public Builder setCPRNR(CharSequence value) {
      validate(fields()[3], value);
      this.CPR_NR = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_NR' field has been set.
      * @return True if the 'CPR_NR' field has been set, false otherwise.
      */
    public boolean hasCPRNR() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CPR_NR' field.
      * @return This builder.
      */
    public Builder clearCPRNR() {
      CPR_NR = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'M_K_KODE' field.
      * @return The value.
      */
    public CharSequence getMKKODE() {
      return M_K_KODE;
    }

    /**
      * Sets the value of the 'M_K_KODE' field.
      * @param value The value of 'M_K_KODE'.
      * @return This builder.
      */
    public Builder setMKKODE(CharSequence value) {
      validate(fields()[4], value);
      this.M_K_KODE = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'M_K_KODE' field has been set.
      * @return True if the 'M_K_KODE' field has been set, false otherwise.
      */
    public boolean hasMKKODE() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'M_K_KODE' field.
      * @return This builder.
      */
    public Builder clearMKKODE() {
      M_K_KODE = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'FOEDSELSDATO' field.
      * @return The value.
      */
    public CharSequence getFOEDSELSDATO() {
      return FOEDSELSDATO;
    }

    /**
      * Sets the value of the 'FOEDSELSDATO' field.
      * @param value The value of 'FOEDSELSDATO'.
      * @return This builder.
      */
    public Builder setFOEDSELSDATO(CharSequence value) {
      validate(fields()[5], value);
      this.FOEDSELSDATO = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'FOEDSELSDATO' field has been set.
      * @return True if the 'FOEDSELSDATO' field has been set, false otherwise.
      */
    public boolean hasFOEDSELSDATO() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'FOEDSELSDATO' field.
      * @return This builder.
      */
    public Builder clearFOEDSELSDATO() {
      FOEDSELSDATO = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'FOEDSDAT_AENDR_DOK' field.
      * @return The value.
      */
    public CharSequence getFOEDSDATAENDRDOK() {
      return FOEDSDAT_AENDR_DOK;
    }

    /**
      * Sets the value of the 'FOEDSDAT_AENDR_DOK' field.
      * @param value The value of 'FOEDSDAT_AENDR_DOK'.
      * @return This builder.
      */
    public Builder setFOEDSDATAENDRDOK(CharSequence value) {
      validate(fields()[6], value);
      this.FOEDSDAT_AENDR_DOK = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'FOEDSDAT_AENDR_DOK' field has been set.
      * @return True if the 'FOEDSDAT_AENDR_DOK' field has been set, false otherwise.
      */
    public boolean hasFOEDSDATAENDRDOK() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'FOEDSDAT_AENDR_DOK' field.
      * @return This builder.
      */
    public Builder clearFOEDSDATAENDRDOK() {
      FOEDSDAT_AENDR_DOK = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'PERSON_STATUS_DATO' field.
      * @return The value.
      */
    public CharSequence getPERSONSTATUSDATO() {
      return PERSON_STATUS_DATO;
    }

    /**
      * Sets the value of the 'PERSON_STATUS_DATO' field.
      * @param value The value of 'PERSON_STATUS_DATO'.
      * @return This builder.
      */
    public Builder setPERSONSTATUSDATO(CharSequence value) {
      validate(fields()[7], value);
      this.PERSON_STATUS_DATO = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'PERSON_STATUS_DATO' field has been set.
      * @return True if the 'PERSON_STATUS_DATO' field has been set, false otherwise.
      */
    public boolean hasPERSONSTATUSDATO() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'PERSON_STATUS_DATO' field.
      * @return This builder.
      */
    public Builder clearPERSONSTATUSDATO() {
      PERSON_STATUS_DATO = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'PERSON_STATUS' field.
      * @return The value.
      */
    public CharSequence getPERSONSTATUS() {
      return PERSON_STATUS;
    }

    /**
      * Sets the value of the 'PERSON_STATUS' field.
      * @param value The value of 'PERSON_STATUS'.
      * @return This builder.
      */
    public Builder setPERSONSTATUS(CharSequence value) {
      validate(fields()[8], value);
      this.PERSON_STATUS = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'PERSON_STATUS' field has been set.
      * @return True if the 'PERSON_STATUS' field has been set, false otherwise.
      */
    public boolean hasPERSONSTATUS() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'PERSON_STATUS' field.
      * @return This builder.
      */
    public Builder clearPERSONSTATUS() {
      PERSON_STATUS = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'PERSON_STATUS_DOK' field.
      * @return The value.
      */
    public CharSequence getPERSONSTATUSDOK() {
      return PERSON_STATUS_DOK;
    }

    /**
      * Sets the value of the 'PERSON_STATUS_DOK' field.
      * @param value The value of 'PERSON_STATUS_DOK'.
      * @return This builder.
      */
    public Builder setPERSONSTATUSDOK(CharSequence value) {
      validate(fields()[9], value);
      this.PERSON_STATUS_DOK = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'PERSON_STATUS_DOK' field has been set.
      * @return True if the 'PERSON_STATUS_DOK' field has been set, false otherwise.
      */
    public boolean hasPERSONSTATUSDOK() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'PERSON_STATUS_DOK' field.
      * @return This builder.
      */
    public Builder clearPERSONSTATUSDOK() {
      PERSON_STATUS_DOK = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_DATA_FORSKEL' field.
      * @return The value.
      */
    public CharSequence getCPRDATAFORSKEL() {
      return CPR_DATA_FORSKEL;
    }

    /**
      * Sets the value of the 'CPR_DATA_FORSKEL' field.
      * @param value The value of 'CPR_DATA_FORSKEL'.
      * @return This builder.
      */
    public Builder setCPRDATAFORSKEL(CharSequence value) {
      validate(fields()[10], value);
      this.CPR_DATA_FORSKEL = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_DATA_FORSKEL' field has been set.
      * @return True if the 'CPR_DATA_FORSKEL' field has been set, false otherwise.
      */
    public boolean hasCPRDATAFORSKEL() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'CPR_DATA_FORSKEL' field.
      * @return This builder.
      */
    public Builder clearCPRDATAFORSKEL() {
      CPR_DATA_FORSKEL = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_ADR_OPD' field.
      * @return The value.
      */
    public CharSequence getCPRADROPD() {
      return CPR_ADR_OPD;
    }

    /**
      * Sets the value of the 'CPR_ADR_OPD' field.
      * @param value The value of 'CPR_ADR_OPD'.
      * @return This builder.
      */
    public Builder setCPRADROPD(CharSequence value) {
      validate(fields()[11], value);
      this.CPR_ADR_OPD = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_ADR_OPD' field has been set.
      * @return True if the 'CPR_ADR_OPD' field has been set, false otherwise.
      */
    public boolean hasCPRADROPD() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'CPR_ADR_OPD' field.
      * @return This builder.
      */
    public Builder clearCPRADROPD() {
      CPR_ADR_OPD = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_FORNAVN_OPD' field.
      * @return The value.
      */
    public CharSequence getCPRFORNAVNOPD() {
      return CPR_FORNAVN_OPD;
    }

    /**
      * Sets the value of the 'CPR_FORNAVN_OPD' field.
      * @param value The value of 'CPR_FORNAVN_OPD'.
      * @return This builder.
      */
    public Builder setCPRFORNAVNOPD(CharSequence value) {
      validate(fields()[12], value);
      this.CPR_FORNAVN_OPD = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_FORNAVN_OPD' field has been set.
      * @return True if the 'CPR_FORNAVN_OPD' field has been set, false otherwise.
      */
    public boolean hasCPRFORNAVNOPD() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'CPR_FORNAVN_OPD' field.
      * @return This builder.
      */
    public Builder clearCPRFORNAVNOPD() {
      CPR_FORNAVN_OPD = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_EFTERNAVN_OPD' field.
      * @return The value.
      */
    public CharSequence getCPREFTERNAVNOPD() {
      return CPR_EFTERNAVN_OPD;
    }

    /**
      * Sets the value of the 'CPR_EFTERNAVN_OPD' field.
      * @param value The value of 'CPR_EFTERNAVN_OPD'.
      * @return This builder.
      */
    public Builder setCPREFTERNAVNOPD(CharSequence value) {
      validate(fields()[13], value);
      this.CPR_EFTERNAVN_OPD = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_EFTERNAVN_OPD' field has been set.
      * @return True if the 'CPR_EFTERNAVN_OPD' field has been set, false otherwise.
      */
    public boolean hasCPREFTERNAVNOPD() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'CPR_EFTERNAVN_OPD' field.
      * @return This builder.
      */
    public Builder clearCPREFTERNAVNOPD() {
      CPR_EFTERNAVN_OPD = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_NR_OPLYST_KODE' field.
      * @return The value.
      */
    public CharSequence getCPRNROPLYSTKODE() {
      return CPR_NR_OPLYST_KODE;
    }

    /**
      * Sets the value of the 'CPR_NR_OPLYST_KODE' field.
      * @param value The value of 'CPR_NR_OPLYST_KODE'.
      * @return This builder.
      */
    public Builder setCPRNROPLYSTKODE(CharSequence value) {
      validate(fields()[14], value);
      this.CPR_NR_OPLYST_KODE = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_NR_OPLYST_KODE' field has been set.
      * @return True if the 'CPR_NR_OPLYST_KODE' field has been set, false otherwise.
      */
    public boolean hasCPRNROPLYSTKODE() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'CPR_NR_OPLYST_KODE' field.
      * @return This builder.
      */
    public Builder clearCPRNROPLYSTKODE() {
      CPR_NR_OPLYST_KODE = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'CPR_NR_AENDR_DOK' field.
      * @return The value.
      */
    public CharSequence getCPRNRAENDRDOK() {
      return CPR_NR_AENDR_DOK;
    }

    /**
      * Sets the value of the 'CPR_NR_AENDR_DOK' field.
      * @param value The value of 'CPR_NR_AENDR_DOK'.
      * @return This builder.
      */
    public Builder setCPRNRAENDRDOK(CharSequence value) {
      validate(fields()[15], value);
      this.CPR_NR_AENDR_DOK = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'CPR_NR_AENDR_DOK' field has been set.
      * @return True if the 'CPR_NR_AENDR_DOK' field has been set, false otherwise.
      */
    public boolean hasCPRNRAENDRDOK() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'CPR_NR_AENDR_DOK' field.
      * @return This builder.
      */
    public Builder clearCPRNRAENDRDOK() {
      CPR_NR_AENDR_DOK = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'KALDE_FORNAVN_MRK' field.
      * @return The value.
      */
    public CharSequence getKALDEFORNAVNMRK() {
      return KALDE_FORNAVN_MRK;
    }

    /**
      * Sets the value of the 'KALDE_FORNAVN_MRK' field.
      * @param value The value of 'KALDE_FORNAVN_MRK'.
      * @return This builder.
      */
    public Builder setKALDEFORNAVNMRK(CharSequence value) {
      validate(fields()[16], value);
      this.KALDE_FORNAVN_MRK = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'KALDE_FORNAVN_MRK' field has been set.
      * @return True if the 'KALDE_FORNAVN_MRK' field has been set, false otherwise.
      */
    public boolean hasKALDEFORNAVNMRK() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'KALDE_FORNAVN_MRK' field.
      * @return This builder.
      */
    public Builder clearKALDEFORNAVNMRK() {
      KALDE_FORNAVN_MRK = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'TJM_KODE' field.
      * @return The value.
      */
    public CharSequence getTJMKODE() {
      return TJM_KODE;
    }

    /**
      * Sets the value of the 'TJM_KODE' field.
      * @param value The value of 'TJM_KODE'.
      * @return This builder.
      */
    public Builder setTJMKODE(CharSequence value) {
      validate(fields()[17], value);
      this.TJM_KODE = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'TJM_KODE' field has been set.
      * @return True if the 'TJM_KODE' field has been set, false otherwise.
      */
    public boolean hasTJMKODE() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'TJM_KODE' field.
      * @return This builder.
      */
    public Builder clearTJMKODE() {
      TJM_KODE = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'STILLING_DATO' field.
      * @return The value.
      */
    public CharSequence getSTILLINGDATO() {
      return STILLING_DATO;
    }

    /**
      * Sets the value of the 'STILLING_DATO' field.
      * @param value The value of 'STILLING_DATO'.
      * @return This builder.
      */
    public Builder setSTILLINGDATO(CharSequence value) {
      validate(fields()[18], value);
      this.STILLING_DATO = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'STILLING_DATO' field has been set.
      * @return True if the 'STILLING_DATO' field has been set, false otherwise.
      */
    public boolean hasSTILLINGDATO() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'STILLING_DATO' field.
      * @return This builder.
      */
    public Builder clearSTILLINGDATO() {
      STILLING_DATO = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'RET_SBH' field.
      * @return The value.
      */
    public CharSequence getRETSBH() {
      return RET_SBH;
    }

    /**
      * Sets the value of the 'RET_SBH' field.
      * @param value The value of 'RET_SBH'.
      * @return This builder.
      */
    public Builder setRETSBH(CharSequence value) {
      validate(fields()[19], value);
      this.RET_SBH = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'RET_SBH' field has been set.
      * @return True if the 'RET_SBH' field has been set, false otherwise.
      */
    public boolean hasRETSBH() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'RET_SBH' field.
      * @return This builder.
      */
    public Builder clearRETSBH() {
      RET_SBH = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'RET_TIMESTAMP' field.
      * @return The value.
      */
    public CharSequence getRETTIMESTAMP() {
      return RET_TIMESTAMP;
    }

    /**
      * Sets the value of the 'RET_TIMESTAMP' field.
      * @param value The value of 'RET_TIMESTAMP'.
      * @return This builder.
      */
    public Builder setRETTIMESTAMP(CharSequence value) {
      validate(fields()[20], value);
      this.RET_TIMESTAMP = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'RET_TIMESTAMP' field has been set.
      * @return True if the 'RET_TIMESTAMP' field has been set, false otherwise.
      */
    public boolean hasRETTIMESTAMP() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'RET_TIMESTAMP' field.
      * @return This builder.
      */
    public Builder clearRETTIMESTAMP() {
      RET_TIMESTAMP = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'STILLING' field.
      * @return The value.
      */
    public CharSequence getSTILLING() {
      return STILLING;
    }

    /**
      * Sets the value of the 'STILLING' field.
      * @param value The value of 'STILLING'.
      * @return This builder.
      */
    public Builder setSTILLING(CharSequence value) {
      validate(fields()[21], value);
      this.STILLING = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'STILLING' field has been set.
      * @return True if the 'STILLING' field has been set, false otherwise.
      */
    public boolean hasSTILLING() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'STILLING' field.
      * @return This builder.
      */
    public Builder clearSTILLING() {
      STILLING = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public DataOrg build() {
      try {
        DataOrg record = new DataOrg();
        record.FF_NR = fieldSetFlags()[0] ? this.FF_NR : (CharSequence) defaultValue(fields()[0]);
        record.FORNAVN = fieldSetFlags()[1] ? this.FORNAVN : (CharSequence) defaultValue(fields()[1]);
        record.EFTERNAVN = fieldSetFlags()[2] ? this.EFTERNAVN : (CharSequence) defaultValue(fields()[2]);
        record.CPR_NR = fieldSetFlags()[3] ? this.CPR_NR : (CharSequence) defaultValue(fields()[3]);
        record.M_K_KODE = fieldSetFlags()[4] ? this.M_K_KODE : (CharSequence) defaultValue(fields()[4]);
        record.FOEDSELSDATO = fieldSetFlags()[5] ? this.FOEDSELSDATO : (CharSequence) defaultValue(fields()[5]);
        record.FOEDSDAT_AENDR_DOK = fieldSetFlags()[6] ? this.FOEDSDAT_AENDR_DOK : (CharSequence) defaultValue(fields()[6]);
        record.PERSON_STATUS_DATO = fieldSetFlags()[7] ? this.PERSON_STATUS_DATO : (CharSequence) defaultValue(fields()[7]);
        record.PERSON_STATUS = fieldSetFlags()[8] ? this.PERSON_STATUS : (CharSequence) defaultValue(fields()[8]);
        record.PERSON_STATUS_DOK = fieldSetFlags()[9] ? this.PERSON_STATUS_DOK : (CharSequence) defaultValue(fields()[9]);
        record.CPR_DATA_FORSKEL = fieldSetFlags()[10] ? this.CPR_DATA_FORSKEL : (CharSequence) defaultValue(fields()[10]);
        record.CPR_ADR_OPD = fieldSetFlags()[11] ? this.CPR_ADR_OPD : (CharSequence) defaultValue(fields()[11]);
        record.CPR_FORNAVN_OPD = fieldSetFlags()[12] ? this.CPR_FORNAVN_OPD : (CharSequence) defaultValue(fields()[12]);
        record.CPR_EFTERNAVN_OPD = fieldSetFlags()[13] ? this.CPR_EFTERNAVN_OPD : (CharSequence) defaultValue(fields()[13]);
        record.CPR_NR_OPLYST_KODE = fieldSetFlags()[14] ? this.CPR_NR_OPLYST_KODE : (CharSequence) defaultValue(fields()[14]);
        record.CPR_NR_AENDR_DOK = fieldSetFlags()[15] ? this.CPR_NR_AENDR_DOK : (CharSequence) defaultValue(fields()[15]);
        record.KALDE_FORNAVN_MRK = fieldSetFlags()[16] ? this.KALDE_FORNAVN_MRK : (CharSequence) defaultValue(fields()[16]);
        record.TJM_KODE = fieldSetFlags()[17] ? this.TJM_KODE : (CharSequence) defaultValue(fields()[17]);
        record.STILLING_DATO = fieldSetFlags()[18] ? this.STILLING_DATO : (CharSequence) defaultValue(fields()[18]);
        record.RET_SBH = fieldSetFlags()[19] ? this.RET_SBH : (CharSequence) defaultValue(fields()[19]);
        record.RET_TIMESTAMP = fieldSetFlags()[20] ? this.RET_TIMESTAMP : (CharSequence) defaultValue(fields()[20]);
        record.STILLING = fieldSetFlags()[21] ? this.STILLING : (CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
