package wikiedits;/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Myrecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5908711412832582818L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Myrecord\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence f1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Myrecord() {}

  /**
   * All-args constructor.
   * @param f1 The new value for f1
   */
  public Myrecord(java.lang.CharSequence f1) {
    this.f1 = f1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return f1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: f1 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   * @return The value of the 'f1' field.
   */
  public java.lang.CharSequence getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   * @param value the value to set.
   */
  public void setF1(java.lang.CharSequence value) {
    this.f1 = value;
  }

  /**
   * Creates a new Myrecord RecordBuilder.
   * @return A new Myrecord RecordBuilder
   */
  public static Myrecord.Builder newBuilder() {
    return new Myrecord.Builder();
  }

  /**
   * Creates a new Myrecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Myrecord RecordBuilder
   */
  public static Myrecord.Builder newBuilder(Myrecord.Builder other) {
    return new Myrecord.Builder(other);
  }

  /**
   * Creates a new Myrecord RecordBuilder by copying an existing Myrecord instance.
   * @param other The existing instance to copy.
   * @return A new Myrecord RecordBuilder
   */
  public static Myrecord.Builder newBuilder(Myrecord other) {
    return new Myrecord.Builder(other);
  }

  /**
   * RecordBuilder for Myrecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Myrecord>
    implements org.apache.avro.data.RecordBuilder<Myrecord> {

    private java.lang.CharSequence f1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Myrecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Myrecord instance
     * @param other The existing instance to copy.
     */
    private Builder(Myrecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'f1' field.
      * @return The value.
      */
    public java.lang.CharSequence getF1() {
      return f1;
    }

    /**
      * Sets the value of the 'f1' field.
      * @param value The value of 'f1'.
      * @return This builder.
      */
    public Myrecord.Builder setF1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'f1' field has been set.
      * @return True if the 'f1' field has been set, false otherwise.
      */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'f1' field.
      * @return This builder.
      */
    public Myrecord.Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Myrecord build() {
      try {
        Myrecord record = new Myrecord();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
